name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
        env:
          # https://github.com/actions/setup-node/issues/531#issuecomment-1819151412
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Install Dependencies
        run: yarn --immutable
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      # required for linting before commit
      - name: Build
        run: yarn build
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
